void csr_grid_fill_4th(
	csr_matrix A, 
	const MKL_INT dim,
	const MKL_INT ghost,
	const double dr,
	const double *u,
	const double m,
	const MKL_INT r_sym[GNUM],
	const MKL_INT bound_order[GNUM],
	const MKL_INT nnz[GNUM],
	const MKL_INT p_c[GNUM],
	const MKL_INT p_s[GNUM],
	const MKL_INT p_bound[GNUM],
	void (*j_c)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const double,
		const double, const double,
		double, double, double, double, double,
		double, double, double, double, double,
		double, double, double, double, double,
		const MKL_INT, const MKL_INT, const MKL_INT),
	void (*j_s)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const double,
		const double, const double,
		double, double, double, double, double, double,
		double, double, double, double, double, double,
		double, double, double, double, double, double,
		const MKL_INT, const MKL_INT, const MKL_INT));